project:
  type: website
  output-dir: docs
        
render:
    - "*.qmd"
    
website:
  title: ""
  search: false 
  site-url: "https://paula-montano.github.io/"
  site-path: ""
  repo-url: "https://github.com/paula-montano/paula-montano.github.io.git"
  
  navbar:
    pinned: true 
    
    right:
      - href: about.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: awards.qmd
        text: Awards
      - href: code.qmd
        text: Code
      - href: CV_Montano_Paula.pdf
        text: CV

  page-footer:
      center: |
        <span><i class="bi bi-cc-circle"></i> 2024 Paula Montano</span>\
        All rights reserved.
      right: |
        <span>Made with <i class="bi bi-r-circle-fill"></i> and <a href="https://quarto.org/" target="_blank">Quarto</a></span>
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false


