---
title: "Research"
toc: true 
link-external-newwindow: true
---

## Working Papers 

**Exceptional Measures for Exceptional Times: Deciphering Emergency Politics Motivators in the Council of the European Union in the Euro Crisis** (Paula Montano).\
<details>
<summary>Abstract</summary>
::: {.justify}

In recent years, the EU's crisis responses have become increasingly susceptible to emergency rule. Recent scholarship argues for the prevalence of emergency politics—a distinct mode of governance—among EU institutions. This paper uncovers the dynamics of emergency governance in the Council of the European Union during ECOFIN debates in the euro crisis. Leveraging the Debates of the Council of the European Union (DICEU) dataset from 2010 to 2016, this study employs quantitative text analysis and a two-part econometric model to identify patterns of emergency language use and its determinants. Higher intensity emergency language is associated with executive leaders from larger country contributors to EU lending during critical debates in peak crisis years. In contrast, executive leaders from member states in EFSF/ESM financial assistance programs notably suppressed such communication during their active program years. This divergence suggests that crisis-led economic policy responses—specifically, conditionalities in financial assistance programs—shape crisis communication strategies within EU institutions.

:::
</details>

**Crisis as a Catalyst for Rebellion: Party Disloyalty and Grandstanding in Parliamentary Debates during Economic Crises** (Paula Montano).\
<details>
<summary>Abstract</summary>
::: {.justify}

Studies show that backbench rebellions in parliament are on the rise. This behavior is often expressed through position-taking, party disloyalty, and credit-claiming. However, less is known about the implications of rebellion during crises, particularly for government parties. Drawing on the literature on parliamentary rebellion, this paper explores how Members of Parliament (TDs) in Ireland resort to strategic messaging—specifically, grandstanding in legislative debates—during the euro crisis to differentiate themselves from the party line and connect with constituents. Combining the ParlEE dataset and the Database of Parliamentary Speeches in Ireland, to cover highly polarized budget debates, this study employs LLMs and text analysis techniques to examine how government backbenchers communicate when challenging their party line. The evidence suggests that government backbenchers engage in strategic communication to express dissent in polarised budget debates when crisis pressures are high, potentially undermining government cohesion during crises.

:::
</details>

**Grandstanding under the Spotlight: Unveiling Elites Crisis Communication in the Council of the European Union** (with <a href="https://people.ucd.ie/james.cross/">James P. Cross</a> and <a href="https://davidycliao.github.io/">Yen-Chieh Liao</a>).\
<details>
<summary>Abstract</summary>
::: {.justify}

Exceptional times affect how elites communicate and adopt economic policy positions in international negotiations. This paper examines how ministers in the Economic and Financial Affairs Council strategically resort to grandstanding communication to set agendas in response to the Euro crisis between 2010 and 2016. Using few-shot learning with large language models to identify grandstanding statements, combined with a difference-in-differences design, we find that national economic pressures during the euro crisis led ministers from Eurosceptic governments to engage in grandstanding behaviour more than those from Europhile governments. Our results show evidence that pro-EU and Eurosceptic governments may adopt different political communication strategies in response to varying degrees of economic pressures during the crisis.

:::
</details>

If you would like to get access to the latest version of a paper, feel free to [e-mail me](mailto:paula.montano1@gmail.com).


